[package]
name = "kvbencher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
hdrhistogram = "7.5.4"
rand = "0.9.2"
rand_distr = "0.5.1"
redb = "3.1.0"
sled = "0.34.7"
tempfile = "3.23.0"
thousands = "0.2.0"
